#! /bin/sh

echo $HOSTNAME | grep linux11107.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 28663 
else 
rsh linux11107.dc.engr.scu.edu kill 28663 
 sleep 10 
rsh linux11107.dc.engr.scu.edu kill -9 28663 
fi
