#! /bin/sh

echo $HOSTNAME | grep linux11104.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 12627 
else 
rsh linux11104.dc.engr.scu.edu kill 12627 
 sleep 10 
rsh linux11104.dc.engr.scu.edu kill -9 12627 
fi
