#! /bin/sh

echo $HOSTNAME | grep linux11104.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 12058 
else 
rsh linux11104.dc.engr.scu.edu kill 12058 
 sleep 10 
rsh linux11104.dc.engr.scu.edu kill -9 12058 
fi
