#! /bin/sh

echo $HOSTNAME | grep linux11107.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 829 
else 
rsh linux11107.dc.engr.scu.edu kill 829 
 sleep 10 
rsh linux11107.dc.engr.scu.edu kill -9 829 
fi
