#! /bin/sh

echo $HOSTNAME | grep linux11112.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 1842 
else 
rsh linux11112.dc.engr.scu.edu kill 1842 
 sleep 10 
rsh linux11112.dc.engr.scu.edu kill -9 1842 
fi
