::sa::_backgroundSaeShell::signalProcessReady 1611271873
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/lkim/simulation/LAB2,CMOSInverter_tb,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::exit
