#! /bin/sh

echo $HOSTNAME | grep linux11111.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 22808 
else 
rsh linux11111.dc.engr.scu.edu kill 22808 
 sleep 10 
rsh linux11111.dc.engr.scu.edu kill -9 22808 
fi
