#! /bin/sh

echo $HOSTNAME | grep linux11112.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 21975 
else 
rsh linux11112.dc.engr.scu.edu kill 21975 
 sleep 10 
rsh linux11112.dc.engr.scu.edu kill -9 21975 
fi
