#! /bin/sh

echo $HOSTNAME | grep linux11107.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 32298 
else 
rsh linux11107.dc.engr.scu.edu kill 32298 
 sleep 10 
rsh linux11107.dc.engr.scu.edu kill -9 32298 
fi
