#! /bin/sh

echo $HOSTNAME | grep linux11112.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 5400 
else 
rsh linux11112.dc.engr.scu.edu kill 5400 
 sleep 10 
rsh linux11112.dc.engr.scu.edu kill -9 5400 
fi
