#! /bin/sh

echo $HOSTNAME | grep linux11109.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 11140 
else 
rsh linux11109.dc.engr.scu.edu kill 11140 
 sleep 10 
rsh linux11109.dc.engr.scu.edu kill -9 11140 
fi
