#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /DCNFS/users/student/cazzarel/Tutorial/synopsys_custom/pvjob_Tutorial.NOR.icv.lvs/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /DCNFS/users/student/cazzarel/Tutorial/synopsys_custom/pvjob_Tutorial.NOR.icv.lvs/./TOPCELLNAME_err | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /DCNFS/users/student/cazzarel/Tutorial/synopsys_custom/pvjob_Tutorial.NOR.icv.lvs/NOR.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /DCNFS/users/student/cazzarel/Tutorial/synopsys_custom/pvjob_Tutorial.NOR.icv.lvs/run_details/duse_master.tmp && \
mv /DCNFS/users/student/cazzarel/Tutorial/synopsys_custom/pvjob_Tutorial.NOR.icv.lvs/run_details/duse_master.tmp /DCNFS/users/student/cazzarel/Tutorial/synopsys_custom/pvjob_Tutorial.NOR.icv.lvs/run_details/duse_master
