#! /bin/sh

echo $HOSTNAME | grep linux11108.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 25993 
else 
rsh linux11108.dc.engr.scu.edu kill 25993 
 sleep 10 
rsh linux11108.dc.engr.scu.edu kill -9 25993 
fi
