#! /bin/sh

echo $HOSTNAME | grep linux11114.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 3233 
else 
rsh linux11114.dc.engr.scu.edu kill 3233 
 sleep 10 
rsh linux11114.dc.engr.scu.edu kill -9 3233 
fi
