#! /bin/sh

echo $HOSTNAME | grep linux11112.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 1995 
else 
rsh linux11112.dc.engr.scu.edu kill 1995 
 sleep 10 
rsh linux11112.dc.engr.scu.edu kill -9 1995 
fi
