#! /bin/sh

echo $HOSTNAME | grep linux11110.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 19978 
else 
rsh linux11110.dc.engr.scu.edu kill 19978 
 sleep 10 
rsh linux11110.dc.engr.scu.edu kill -9 19978 
fi
