#! /bin/sh

echo $HOSTNAME | grep linux11104.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 15265 
else 
rsh linux11104.dc.engr.scu.edu kill 15265 
 sleep 10 
rsh linux11104.dc.engr.scu.edu kill -9 15265 
fi
