#! /bin/sh

echo $HOSTNAME | grep linux11104.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 31584 
else 
rsh linux11104.dc.engr.scu.edu kill 31584 
 sleep 10 
rsh linux11104.dc.engr.scu.edu kill -9 31584 
fi
