#! /bin/sh

echo $HOSTNAME | grep linux11112.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 8926 
else 
rsh linux11112.dc.engr.scu.edu kill 8926 
 sleep 10 
rsh linux11112.dc.engr.scu.edu kill -9 8926 
fi
