#! /bin/sh

echo $HOSTNAME | grep linux11112.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 14654 
else 
rsh linux11112.dc.engr.scu.edu kill 14654 
 sleep 10 
rsh linux11112.dc.engr.scu.edu kill -9 14654 
fi
