::sa::_backgroundSaeShell::signalProcessReady 1611344031
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession1 testbenchName default resultsDir /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal databaseName /DCNFS/users/student/cazzarel/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::exit
